spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartPetFeeder?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 147258wang
    driver-class-name: com.mysql.cj.jdbc.Driver

feeder:
  server:
    ip: 8.130.100.214
    port: 8080

image:
  dir:
    path: file:/home/wfh/feeder/images/

wechat:
  appId: wxc14bf5a28502fbc6
  appSecret: d558504d3dbf83bd9fa195ea11a3e872
  foodShortageReminderTemplate: 0dOyY-AkpujqvTYLOMdRZa8BLvgkCgNf2cTRXM7LpU4
  petFeedingReminderTemplate: 7nIvqLHkwu5Q0nXhKu2VeaUwPUNJuh2oaPaz9mTP8Yc
