spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartPetFeeder?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 147258wang
    driver-class-name: com.mysql.cj.jdbc.Driver